
### 회원 가입
POST localhost:8080/auth/signup
Content-Type: application/json

{
  "email" : "khghouse@daum.net",
  "password" : "Khghouse12!@"
}

### 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email" : "khghouse@daum.net",
  "password" : "Khghouse12!@"
}
