
### 회원 가입
POST localhost:8080/auth/signup
Content-Type: application/json

{
  "email" : "khghouse@daum.net",
  "password" : "Khghouse12!@"
}

### 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email" : "khghouse@daum.net",
  "password" : "Khghouse12!@"
}

### 토큰 재발행
POST localhost:8080/auth/token/reissue
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraGdob3VzZUBkYXVtLm5ldCIsIm1lbWJlcklkIjoxLCJlbWFpbCI6ImtoZ2hvdXNlQGRhdW0ubmV0IiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE3MTI5Mjg0NDl9._k2AxIpV-W6kyqoczPJ1OKpDuy2IKvh8wEWkhBPzzIc",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTU1MjA0MTl9.JRrCN1TjAD_dicoR5GG242Z7NwdTZsMJvhVUFK5hncM"
}

### 로그아웃
POST localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraGdob3VzZUBkYXVtLm5ldCIsIm1lbWJlcklkIjoxLCJlbWFpbCI6ImtoZ2hvdXNlQGRhdW0ubmV0IiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE3MTMxMDYzOTV9.W_5M2OCj-6uX6FIi_SZPXDlSmEMoI4qSm3srIWWrkEc
